export const customerBookingCopy = {
  serviceOptions: ["목욕", "부분 미용", "전체 미용", "기타 / 잘 모르겠어요"] as const,
  heroEyebrow: "처음 오는 고객도 가볍게 시작하는 예약 페이지",
  heroTitleSuffix: "모바일 예약",
  heroBody: "원하는 흐름을 바로 선택해서 들어갈 수 있게 구성했어요.",
  modes: {
    first: {
      title: "첫 방문 예약",
      description: "처음 오는 아기라면 여기서 가장 빠르게 예약을 시작해요.",
    },
    returning: {
      title: "재방문 예약",
      description: "지난 방문 정보를 불러와 더 짧게 다시 예약하는 흐름이에요.",
    },
    manage: {
      title: "예약 확인 / 취소 / 변경",
      description: "연락처로 바로 조회하고 확인할 수 있어요.",
    },
  },
  common: {
    backToHome: "← 처음 화면으로",
    next: "다음",
    prev: "이전",
    submit: "예약 남기기",
    goHome: "처음 화면으로 돌아가기",
    lookup: "조회",
    lookupPhonePlaceholder: "연락처 입력",
    reservationCompleteTitle: "예약 접수 완료",
    noLookupResult: "해당 연락처로 조회된 예약이 없어요.",
    noStyleMemo: "스타일 메모 없음",
    reservationFallback: "예약",
    statusLabel: "상태",
    recentRecord: "지난 기록",
    priceGuide: "최종 금액은 견종, 크기, 털 상태, 미용 난이도에 따라 달라질 수 있어요.",
  },
  firstVisit: {
    title: "첫 방문 예약",
    successSubtitle: "첫 방문 예약이 가볍게 접수되었어요.",
    successManual: "예약 요청을 남겼어요. 매장에서 확인 후 연락드릴게요.",
    successAuto: "예약 요청이 접수됐어요. 안내 메시지를 확인해 주세요.",
    guardianSuffix: " 보호자",
    memoBreed: "견종",
    memoNote: "참고",
    memoNoPhoto: "사진 없이 진행",
    memoPhoto: "사진 첨부",
    steps: {
      basic: {
        title: "기본 정보",
        subtitle: "먼저 꼭 필요한 정보부터 받을게요.",
        ownerName: "보호자 이름",
        phone: "연락처",
        babyName: "아기 이름",
        breed: "견종",
      },
      reservation: {
        title: "예약 정보",
        subtitle: "오늘부터 8일 안에서 날짜와 시간을 선택해 주세요.",
      },
      grooming: {
        title: "미용 정보",
        subtitle: "원하는 서비스만 가볍게 선택해 주세요.",
        emptyPrice: "서비스 선택 후 기준가와 안내를 보여드려요.",
      },
      optional: {
        title: "선택 입력",
        subtitle: "없으면 건너뛰어도 괜찮아요.",
        notePlaceholder: "참고사항 한 줄",
      },
    },
  },
  returning: {
    title: "재방문 예약",
    successSubtitle: "재방문 예약이 빠르게 접수되었어요.",
    successSame: "지난번과 같은 서비스로 빠르게 예약 요청을 남겼어요.",
    successDifferent: "변경 내용을 반영해 예약 요청을 남겼어요.",
    lookupError: "지난 방문 정보를 찾지 못했어요. 연락처와 아기 이름을 다시 확인해 주세요.",
    lookupFail: "조회에 실패했어요.",
    noServiceInfo: "지난 서비스 정보 없음",
    noVisitInfo: "방문 기록 없음",
    noLastNote: "지난 참고사항이 없어요.",
    changedService: "변경 서비스",
    sameService: "지난번과 같은 서비스",
    steps: {
      customer: {
        title: "고객 확인",
        subtitle: "지난 방문 정보를 불러와 빠르게 예약할게요. 연락처와 아기 이름만 입력해 주세요.",
        nextLabel: "지난 방문 불러오기",
      },
      history: {
        title: "지난 방문 내용 확인",
        subtitle: "지난 방문 정보를 확인만 하고 다음으로 넘어가세요.",
        petName: "아기 이름",
        service: "지난 서비스",
        date: "지난 방문일",
        note: "지난 참고사항",
      },
      decision: {
        title: "예약 방식 선택",
        subtitle: "이번 예약 방식을 선택해 주세요.",
        sameTitle: "지난번과 같은 서비스로 예약할게요",
        sameBody: "추가 입력 없이 날짜와 시간만 고르면 바로 끝나요.",
        differentTitle: "다른 서비스로 예약할게요",
        differentBody: "날짜와 시간을 고른 뒤 원하는 서비스만 한 번 더 알려주세요.",
      },
      reservation: {
        title: "예약 정보",
        subtitle: "오늘부터 8일 안에서 날짜와 시간을 선택해 주세요.",
        sameSubmit: "바로 예약 접수",
      },
      extra: {
        title: "추가 입력",
        subtitle: "다른 서비스일 때만 필요한 내용만 받을게요.",
        notePlaceholder: "참고사항 한 줄",
        emptyPrice: "서비스 선택 후 기준가와 안내를 보여드려요.",
      },
    },
  },
  reservationPicker: {
    dateLabel: "희망 날짜 선택",
    timeLabel: "희망 시간 선택",
    today: "오늘",
    chooseDateFirst: "날짜를 먼저 선택하면 시간 선택이 열려요.",
  },
  photo: {
    skip: "사진 없이 진행할게요",
    selected: "선택한 사진",
  },
  manage: {
    title: "예약 확인 / 취소 / 변경",
    subtitle: "한 번에 조회할 수 있도록 묶어 두었어요.",
  },
  errors: {
    requestFailed: "요청에 실패했습니다.",
  },
} as const;
