import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import ts from 'typescript';
const datesApi={}; vm.runInNewContext(ts.transpileModule(readFileSync(new URL('../src/lib/initial-setup-closed-dates.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:datesApi,require:createRequire(import.meta.url)});
const file=readFileSync(new URL('../src/server/owner-mutations.ts',import.meta.url),'utf8');
const tree=ts.createSourceFile('mutation.ts',file,ts.ScriptTarget.Latest,true);
const fn=tree.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='updateInitialSetupShopSettings').getText(tree);
function setup(current,conflict=false){const calls=[];const q={select:(...a)=>{calls.push(['select',...a]);return q},eq:(...a)=>{calls.push(['eq',...a]);return q},is:(...a)=>{calls.push(['is',...a]);return q},update:v=>{calls.push(['update',v]);return q},single:async()=>({data:current,error:null}),maybeSingle:async()=>({data:conflict?null:{id:'shop'},error:null})};const exports={};vm.runInNewContext(ts.transpileModule(fn,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,mergeTemporaryClosedDates:datesApi.mergeTemporaryClosedDates,initialSetupShopSettingsSchema:{parse:x=>x},hasSupabaseServerEnv:()=>true,getSupabaseAdmin:()=>({from:()=>q}),nowIso:()=> 'new-version'});return {run:exports.updateInitialSetupShopSettings,calls};}
const payload={shopId:'shop',regularClosedCycle:'biweekly',regularClosedAnchorDate:'2026-09-21',regularClosedDays:[1],bookingAvailableStartTime:'09:00',bookingAvailableEndTime:'19:00',businessHours:{1:{enabled:true,open:'09:00',close:'19:00'}},temporaryClosedDates:[]};
test('narrow save preserves policy JSON and synchronizes recurring fields with CAS',async()=>{const policy={booking_close_grace_minutes:30,customFutureKey:{x:1},regular_closed_cycle:'weekly'};const {run,calls}=setup({reservation_policy_settings:policy,updated_at:'old-version'});await run(payload);const write=calls.find(c=>c[0]==='update')[1];assert.equal(write.regular_closed_cycle,'biweekly');assert.equal(write.reservation_policy_settings.regular_closed_cycle,'biweekly');assert.equal(write.reservation_policy_settings.regular_closed_anchor_date,'2026-09-21');assert.equal(write.reservation_policy_settings.booking_close_grace_minutes,30);assert.deepEqual(write.reservation_policy_settings.customFutureKey,{x:1});assert.ok(calls.some(c=>c[0]==='eq'&&c[1]==='updated_at'&&c[2]==='old-version'));assert.ok(!('concurrent_capacity' in write));});
test('concurrent change rejects rather than returning successful save',async()=>{const {run}=setup({reservation_policy_settings:{},updated_at:'old'},true);await assert.rejects(run(payload),/다른 화면/);});
test('null revision uses IS NULL and non-biweekly clears stale anchor',async()=>{const {run,calls}=setup({reservation_policy_settings:{},updated_at:null});await run({...payload,regularClosedCycle:'monthly_1_3'});assert.ok(calls.some(c=>c[0]==='is'&&c[1]==='updated_at'&&c[2]===null));const write=calls.find(c=>c[0]==='update')[1];assert.equal(write.regular_closed_anchor_date,null);assert.equal(write.reservation_policy_settings.regular_closed_anchor_date,null);});

test('wizard preserves current temporary closures and rejects invalid recurring inputs before writing',async()=>{const {run,calls}=setup({reservation_policy_settings:{},updated_at:'old',temporary_closed_dates:['2026-10-01']});await run(payload,{preserveTemporaryClosedDates:true});assert.deepEqual(calls.find(c=>c[0]==='update')[1].temporary_closed_dates,['2026-10-01']);for(const anchor of [null,'2026-02-30','invalid'])await assert.rejects(run({...payload,regularClosedAnchorDate:anchor}));await assert.rejects(run({...payload,businessHours:{1:{enabled:false,open:'09:00',close:'19:00'}}}));assert.equal(calls.filter(c=>c[0]==='update').length,1);});

test('explicit date delta preserves concurrent dates, adds selections and removes deselections',async()=>{const {run,calls}=setup({reservation_policy_settings:{},updated_at:'old',temporary_closed_dates:['2026-10-01','2026-10-02']});await run(payload,{preserveTemporaryClosedDates:true,temporaryClosedDateChanges:{add:['2026-10-03'],remove:['2026-10-01']}});assert.equal(JSON.stringify(calls.find(c=>c[0]==='update')[1].temporary_closed_dates),JSON.stringify(['2026-10-02','2026-10-03']));});
test('date delta rejects impossible dates, duplicates, intersections, and unknown keys',()=>{for(const change of [{add:['2026-02-30'],remove:[]},{add:['2026-10-01','2026-10-01'],remove:[]},{add:['2026-10-01'],remove:['2026-10-01']},{add:[],remove:[],unknown:1}])assert.equal(datesApi.temporaryClosedDateChangesSchema.safeParse(change).success,false);assert.equal(datesApi.temporaryClosedDateChangesSchema.safeParse({add:['2028-02-29'],remove:[]}).success,true);});
