import type { OwnerBootstrapDto } from "@/types/bootstrap";

const now = "2026-05-11T09:00:00.000Z";

export const ownerBootstrapMock: OwnerBootstrapDto = {
  mode: "mock",
  ownerProfile: {
    email: "owner@example.com",
  },
  shop: {
    id: "mock-shop",
    owner_user_id: "mock-owner",
    name: "포근살롱",
    phone: "02-123-4567",
    address: "서울 마포구 월드컵로 12",
    description: "작은 반려견을 위한 예약제 미용실입니다.",
    business_hours: {
      0: { open: "10:00", close: "18:00", enabled: false },
      1: { open: "10:00", close: "19:00", enabled: true },
      2: { open: "10:00", close: "19:00", enabled: true },
      3: { open: "10:00", close: "19:00", enabled: true },
      4: { open: "10:00", close: "19:00", enabled: true },
      5: { open: "10:00", close: "19:00", enabled: true },
      6: { open: "10:00", close: "18:00", enabled: true },
    },
    regular_closed_days: [0],
    temporary_closed_dates: ["2026-05-15"],
    concurrent_capacity: 2,
    booking_slot_interval_minutes: 30,
    booking_slot_offset_minutes: 0,
    approval_mode: "manual",
    notification_settings: {
      enabled: true,
      revisit_enabled: true,
      booking_confirmed_enabled: true,
      booking_rejected_enabled: true,
      booking_cancelled_enabled: true,
      booking_rescheduled_enabled: true,
      grooming_almost_done_enabled: true,
      grooming_completed_enabled: true,
    },
    customer_page_settings: {
      shop_name: "포근살롱",
      tagline: "반려견이 편안한 미용 시간",
      hero_image_url: "",
      primary_color: "#1f6b5b",
      notices: ["첫 방문은 상담 포함으로 여유 있게 예약해 주세요.", "피부나 건강 이슈는 메모에 남겨 주세요."],
      operating_hours_note: "월-금 10:00-19:00, 토 10:00-18:00",
      holiday_notice: "일요일은 정기 휴무입니다.",
      parking_notice: "건물 뒤편 1대 주차 가능합니다.",
      kakao_inquiry_url: "",
      show_notices: true,
      show_parking_notice: true,
      show_services: true,
      booking_button_label: "예약하기",
      show_kakao_inquiry: false,
      font_preset: "soft",
      font_scale: "comfortable",
    },
    created_at: now,
    updated_at: now,
  },
  guardians: [
    {
      id: "G-1001",
      shop_id: "mock-shop",
      name: "정유진",
      phone: "010-8498-2077",
      memo: "피부가 예민해서 향이 강한 샴푸는 피해주세요.",
      notification_settings: { enabled: true, revisit_enabled: true },
      created_at: now,
      updated_at: now,
    },
    {
      id: "G-1002",
      shop_id: "mock-shop",
      name: "김민지",
      phone: "010-1234-5678",
      memo: "둘째는 드라이 소리에 예민해요.",
      notification_settings: { enabled: true, revisit_enabled: true },
      created_at: now,
      updated_at: now,
    },
    {
      id: "G-1003",
      shop_id: "mock-shop",
      name: "박서준",
      phone: "010-9876-5432",
      memo: "픽업 시간을 꼭 문자로 알려달라고 요청",
      notification_settings: { enabled: true, revisit_enabled: false },
      created_at: now,
      updated_at: now,
    },
    {
      id: "G-1004",
      shop_id: "mock-shop",
      name: "이수현",
      phone: "010-5555-1234",
      memo: "미용 후 발톱 길이 사진 공유 요청",
      notification_settings: { enabled: false, revisit_enabled: false },
      created_at: now,
      updated_at: now,
    },
  ],
  deletedGuardians: [],
  pets: [
    {
      id: "P-1001",
      shop_id: "mock-shop",
      guardian_id: "G-1001",
      name: "우유",
      breed: "비숑",
      weight: 4.8,
      age: 2,
      notes: "피부 민감",
      birthday: "2024-03-12",
      grooming_cycle_weeks: 4,
      avatar_seed: "우",
      created_at: now,
      updated_at: now,
    },
    {
      id: "P-1002",
      shop_id: "mock-shop",
      guardian_id: "G-1002",
      name: "몽이",
      breed: "푸들",
      weight: 5.2,
      age: 4,
      notes: "드라이 소리 예민",
      birthday: "2022-11-02",
      grooming_cycle_weeks: 5,
      avatar_seed: "몽",
      created_at: now,
      updated_at: now,
    },
    {
      id: "P-1003",
      shop_id: "mock-shop",
      guardian_id: "G-1002",
      name: "차이",
      breed: "말티즈",
      weight: 3.9,
      age: 3,
      notes: "",
      birthday: null,
      grooming_cycle_weeks: 6,
      avatar_seed: "차",
      created_at: now,
      updated_at: now,
    },
    {
      id: "P-1004",
      shop_id: "mock-shop",
      guardian_id: "G-1003",
      name: "코코",
      breed: "포메라니안",
      weight: 3.4,
      age: 5,
      notes: "픽업 문자 필수",
      birthday: "2021-08-20",
      grooming_cycle_weeks: 8,
      avatar_seed: "코",
      created_at: now,
      updated_at: now,
    },
    {
      id: "P-1005",
      shop_id: "mock-shop",
      guardian_id: "G-1004",
      name: "보리",
      breed: "시츄",
      weight: 6.1,
      age: 6,
      notes: "발톱 길이 사진 요청",
      birthday: null,
      grooming_cycle_weeks: 4,
      avatar_seed: "보",
      created_at: now,
      updated_at: now,
    },
  ],
  services: [
    {
      id: "S-full",
      shop_id: "mock-shop",
      name: "전체 미용",
      price: 65000,
      price_type: "starting",
      duration_minutes: 120,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "S-bath-trim",
      shop_id: "mock-shop",
      name: "목욕 + 부분정리",
      price: 45000,
      price_type: "starting",
      duration_minutes: 90,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "S-bath",
      shop_id: "mock-shop",
      name: "목욕",
      price: 35000,
      price_type: "fixed",
      duration_minutes: 60,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "S-care",
      shop_id: "mock-shop",
      name: "위생 미용",
      price: 25000,
      price_type: "fixed",
      duration_minutes: 45,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ],
  appointments: [
    {
      id: "R-2401",
      shop_id: "mock-shop",
      guardian_id: "G-1001",
      pet_id: "P-1001",
      service_id: "S-full",
      appointment_date: "2026-05-11",
      appointment_time: "10:30",
      status: "pending",
      memo: "첫 방문 / 피부 민감",
      rejection_reason: null,
      start_at: "2026-05-11T10:30:00.000Z",
      end_at: "2026-05-11T12:30:00.000Z",
      source: "customer",
      created_at: now,
      updated_at: now,
    },
    {
      id: "R-2402",
      shop_id: "mock-shop",
      guardian_id: "G-1002",
      pet_id: "P-1002",
      service_id: "S-bath-trim",
      appointment_date: "2026-05-11",
      appointment_time: "11:30",
      status: "confirmed",
      memo: "픽업 13:00 요청",
      rejection_reason: null,
      start_at: "2026-05-11T11:30:00.000Z",
      end_at: "2026-05-11T13:00:00.000Z",
      source: "customer",
      created_at: now,
      updated_at: now,
    },
    {
      id: "R-2403",
      shop_id: "mock-shop",
      guardian_id: "G-1003",
      pet_id: "P-1004",
      service_id: "S-bath",
      appointment_date: "2026-05-11",
      appointment_time: "13:00",
      status: "in_progress",
      memo: "미용 기록 사진 요청",
      rejection_reason: null,
      start_at: "2026-05-11T13:00:00.000Z",
      end_at: "2026-05-11T14:00:00.000Z",
      source: "owner",
      created_at: now,
      updated_at: now,
    },
    {
      id: "R-2404",
      shop_id: "mock-shop",
      guardian_id: "G-1004",
      pet_id: "P-1005",
      service_id: "S-care",
      appointment_date: "2026-05-11",
      appointment_time: "15:00",
      status: "almost_done",
      memo: "완료 후 알림톡 발송",
      rejection_reason: null,
      start_at: "2026-05-11T15:00:00.000Z",
      end_at: "2026-05-11T15:45:00.000Z",
      source: "owner",
      created_at: now,
      updated_at: now,
    },
    {
      id: "R-2405",
      shop_id: "mock-shop",
      guardian_id: "G-1002",
      pet_id: "P-1003",
      service_id: "S-full",
      appointment_date: "2026-05-11",
      appointment_time: "17:30",
      status: "completed",
      memo: "3주 뒤 재예약 안내 필요",
      rejection_reason: null,
      start_at: "2026-05-11T17:30:00.000Z",
      end_at: "2026-05-11T19:30:00.000Z",
      source: "customer",
      created_at: now,
      updated_at: now,
    },
    {
      id: "R-2406",
      shop_id: "mock-shop",
      guardian_id: "G-1001",
      pet_id: "P-1001",
      service_id: "S-bath",
      appointment_date: "2026-05-12",
      appointment_time: "10:00",
      status: "confirmed",
      memo: "",
      rejection_reason: null,
      start_at: "2026-05-12T10:00:00.000Z",
      end_at: "2026-05-12T11:00:00.000Z",
      source: "customer",
      created_at: now,
      updated_at: now,
    },
  ],
  groomingRecords: [
    {
      id: "GR-1001",
      shop_id: "mock-shop",
      guardian_id: "G-1002",
      pet_id: "P-1002",
      service_id: "S-bath-trim",
      appointment_id: "R-2301",
      style_notes: "얼굴 둥글게, 다리는 짧게",
      memo: "드라이 소리 주의",
      price_paid: 45000,
      groomed_at: "2026-04-28T11:00:00.000Z",
      created_at: now,
      updated_at: now,
    },
    {
      id: "GR-1002",
      shop_id: "mock-shop",
      guardian_id: "G-1003",
      pet_id: "P-1004",
      service_id: "S-bath",
      appointment_id: "R-2302",
      style_notes: "목욕 후 털 말림 꼼꼼히",
      memo: "",
      price_paid: 35000,
      groomed_at: "2026-04-24T13:30:00.000Z",
      created_at: now,
      updated_at: now,
    },
  ],
  notifications: [
    {
      id: "N-1001",
      shop_id: "mock-shop",
      appointment_id: "R-2402",
      pet_id: "P-1002",
      guardian_id: "G-1002",
      type: "booking_confirmed",
      channel: "alimtalk",
      message: "몽이 예약이 확정되었어요.",
      status: "mocked",
      sent_at: null,
      created_at: now,
    },
    {
      id: "N-1002",
      shop_id: "mock-shop",
      appointment_id: "R-2404",
      pet_id: "P-1005",
      guardian_id: "G-1004",
      type: "grooming_almost_done",
      channel: "alimtalk",
      message: "보리 미용이 곧 끝나요.",
      status: "mocked",
      sent_at: null,
      created_at: now,
    },
  ],
};
